# .github/workflows/infrastructure-ci-cd.yml

name: Infrastructure CI/CD Pipeline

on:
  push:
    paths:
      - 'infrastructure/**'
    branches:
      - main
  pull_request:
    paths:
      - 'infrastructure/**'
    branches:
      - main

env:
  AWS_REGION: us-east-1
  CDK_STACK_NAME: gfvrho-infrastructure-stack
  CDK_APP_PATH: infrastructure/cdk
  AWS_ACCOUNT_ID: 123456789012

jobs:
  validate:
    name: Validate Infrastructure Changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install AWS CDK
        run: |
          npm install -g aws-cdk

      - name: Install Dependencies
        run: |
          cd ${{ env.CDK_APP_PATH }}
          npm install

      - name: CDK Synth
        run: |
          cd ${{ env.CDK_APP_PATH }}
          cdk synth

  deploy:
    name: Deploy Infrastructure to AWS
    runs-on: ubuntu-latest
    needs: validate
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github-actions-infra-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install AWS CDK
        run: |
          npm install -g aws-cdk

      - name: Install Dependencies
        run: |
          cd ${{ env.CDK_APP_PATH }}
          npm install

      - name: Deploy Infrastructure
        run: |
          cd ${{ env.CDK_APP_PATH }}
          cdk deploy --require-approval never
